# Generated by Django 6.1.1 on 2026-10-04 17:02

import cases.models
import cases.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('TELECOM', 'Phone, internet or airtime'), ('MOBILE_MONEY', 'Mobile money (M-Pesa, Airtel Money…)'), ('RENT_DEPOSIT', 'Rent deposit not returned'), ('BANK', 'Bank or loan'), ('INSURANCE', 'Insurance claim'), ('EMPLOYER', 'Employer or salary'), ('EDUCATION', 'School, college or university'), ('GOVERNMENT', 'Government office or service'), ('MERCHANT', 'Shop, online seller or delivery'), ('TRAVEL', 'Airline, bus or travel'), ('OTHER', 'Something else')], max_length=20)),
                ('playbook', models.CharField(max_length=40)),
                ('opponent_name', models.CharField(max_length=140, verbose_name='against')),
                ('opponent_contact', models.CharField(blank=True, max_length=140, verbose_name='their email or phone')),
                ('opponent_reference', models.CharField(blank=True, max_length=80, verbose_name='their reference number')),
                ('account_reference', models.CharField(blank=True, max_length=80, verbose_name='your account, phone or policy number with them')),
                ('incident_date', models.DateField(verbose_name='when it happened')),
                ('description', models.TextField(verbose_name='what happened')),
                ('desired_outcome', models.TextField(verbose_name='what you want them to do')),
                ('amount_claimed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='amount at stake (KES)')),
                ('amount_recovered', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('WAITING', 'Waiting for a response'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed without resolution')], default='OPEN', max_length=12)),
                ('outcome_note', models.TextField(blank=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('last_reminded_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('position', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'To do'), ('DONE', 'Done'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=8)),
                ('available_on', models.DateField(blank=True, null=True)),
                ('done_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cases.case')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RECEIPT', 'Receipt or payment proof'), ('MESSAGE', 'SMS, WhatsApp or M-Pesa message'), ('EMAIL', 'Email'), ('CONTRACT', 'Agreement, policy or contract'), ('LETTER', 'Letter or notice'), ('PHOTO', 'Photo'), ('SCREENSHOT', 'Screenshot'), ('OTHER', 'Other document')], max_length=12)),
                ('title', models.CharField(max_length=140)),
                ('file', models.FileField(blank=True, storage=cases.storage.evidence_storage, upload_to=cases.models.evidence_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=200)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('occurred_on', models.DateField(blank=True, null=True, verbose_name='date of this item')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='cases.case')),
            ],
            options={
                'ordering': ['occurred_on', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=200)),
                ('recipient', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_on', models.DateField(blank=True, null=True)),
                ('sent_via', models.CharField(blank=True, max_length=40)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_on', models.DateField()),
                ('kind', models.CharField(choices=[('INCIDENT', 'Problem happened'), ('CONTACTED', 'I contacted them'), ('RESPONSE', 'They responded'), ('NO_RESPONSE', 'No response'), ('LETTER', 'Letter sent'), ('ESCALATED', 'Escalated'), ('PAYMENT', 'Payment or refund'), ('NOTE', 'Note'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('details', models.TextField(blank=True)),
                ('automatic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
                ('evidence', models.ManyToManyField(blank=True, related_name='events', to='cases.evidence')),
            ],
            options={
                'ordering': ['occurred_on', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['owner', 'status'], name='cases_case_owner_i_7e79ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='casestep',
            constraint=models.UniqueConstraint(fields=('case', 'key'), name='unique_step_per_case'),
        ),
    ]
